### ISSUE TITLE
Few minors issues

### ISSUE THREAD

**Issue by codec-abc** [mfelsche/ponylang-mkdocs-theme#1]
Hi,

I tested your theme with my current PR for source code embedding into the docs which is really great. However, I noticed a few very minor issues or things that don't look so nice. You may be already aware of them. If it's the case feel free to close the issue right away.

* The line numbering change color from blue (never visited) to purple (once visited). The problem is that after going to different links there are multiples lines numbers that have the same color.
* When clicking a line number the text becomes orange which is different that the "default" one (purple).
* A scroll into view functionality for the current active line would be great.
* The links to the matching source code takes too much space in my opinion. I would prefer them to be on the same line and smaller too.
* If we could collapse each node on the right it would be easier to find something. The fact that everything is expanded generated a big tree even for a small project. To be fair, this is the behavior of the existing theme but I am not really fund of it. It may be debated though since it surely boils down to personal preference.
* The source code now appears into the search result (I didn't anticipate that with my PR). I don't know if it's good or bad. At most, if possible, I think just the filename should appear in the search result, because the code without proper line break and monospace font is just not readable so there is no point to have it in the search result.

**Comment by mfelsche** [comment]
While i am trying to address all of your concerns here, there seem to be some problems with mkdocs:

- the sources cannot be excluded from the search results right now. We would need to write another search plugin that somehow exludes some files. Here is the current one: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/contrib/legacy_search/__init__.py
- > If we could collapse each node on the right it would be easier to find something.
  Do you mean the TOC on the left or the methods on the right? Should we collapse all the methods? Where? In the source listing or in the documentation of the class/actor?

The other first 3 items are addressed in the next theme update, the 4th needs to be addressed in https://github.com/ponylang/ponyc/pull/2439

**Comment by codec-abc** [comment]
* I just realized I forget to explain the context about the collapsing thing.  I am talking about the tree on the left (despite my previous message saying right). What I think would be great is to have some `+` and '-' to expand the different sections of the tree dynamically. I would start with all collapsed, ie something like that:
```
 * package A
 * package B
... and so on
* source list
```
